sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ybwell

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGdPKNxvczWb9cLLD3A
    access-key-secret: UxKe3HybSgtZvRDZsVlUxa82k0L6Jb
    bucket-name: yb-sky-take-out
